# Generated by Django 6.0.2 on 2026-02-14 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_alter_cliente_email_alter_cliente_telefone'),
        ('filamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_producao', 'Em produção'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('estoque_baixado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PedidoFilamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramas_g', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='filamentos.filamento')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_filamento', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Consumo de filamento do pedido',
                'verbose_name_plural': 'Consumos de filamento do pedido',
            },
        ),
    ]
