# Generated by Django 6.0.2 on 2026-02-15 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filamentos', '0002_filamentoconsumo'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidofilamento',
            name='filamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_pedido', to='filamentos.filamento'),
        ),
    ]
