# Generated by Django 6.0.2 on 2026-02-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedidofilamento_filamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('orcamento', 'Orçamento'), ('aberto', 'Aberto'), ('em_producao', 'Em produção'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='aberto', max_length=20),
        ),
    ]
