# Generated by Django 6.0.2 on 2026-02-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_desconto_pedido_frete_pedido_observacoes_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status'], name='pedido_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['created_at'], name='pedido_created_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente'], name='pedido_cliente_idx'),
        ),
    ]
