# Generated by ChatGPT on 2026-03-01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_pedido_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="prazo_entrega",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedido",
            name="prioridade",
            field=models.CharField(
                choices=[
                    ("baixa", "Baixa"),
                    ("media", "Média"),
                    ("alta", "Alta"),
                    ("urgente", "Urgente"),
                ],
                default="media",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="tempo_estimado_h",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=6),
        ),
        migrations.AddField(
            model_name="pedido",
            name="kanban_order",
            field=models.IntegerField(default=0),
        ),
    ]
