# Generated by Django 6.0.2 on 2026-03-01 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_kanban_campos_producao'),
        ('pedidos', '0006_pedido_kanban_e_tempo_item'),
    ]

    operations = [
    ]
