# Generated by Django 6.0.2 on 2026-02-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cor', models.CharField(blank=True, default='', max_length=60)),
                ('material', models.CharField(choices=[('PLA', 'PLA'), ('PETG', 'PETG'), ('ABS', 'ABS'), ('TPU', 'TPU'), ('OUTRO', 'Outro')], default='PLA', max_length=10)),
                ('peso_inicial_g', models.PositiveIntegerField(default=0)),
                ('peso_atual_g', models.PositiveIntegerField(default=0)),
                ('preco_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome', 'cor', '-updated_at'],
            },
        ),
    ]
