# Generated by Django 6.0.2 on 2026-02-15 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilamentoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramas_g', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('RAS', 'Rascunho'), ('RES', 'Reservado'), ('CON', 'Confirmado'), ('CAN', 'Cancelado')], default='RES', max_length=3)),
                ('referencia', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='filamentos.filamento')),
            ],
        ),
    ]
