# Generated by Django 6.0.2 on 2026-02-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filamentos', '0002_filamentoconsumo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='filamento',
            constraint=models.UniqueConstraint(fields=('nome', 'cor', 'material'), name='uniq_filamento_nome_cor_material'),
        ),
    ]
