# Generated by ChatGPT on 2026-03-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0005_pedido_indexes"),
        ("filamentos", "0003_filamento_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="filamentoconsumo",
            name="pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filamento_consumos",
                to="pedidos.pedido",
            ),
        ),
    ]
